[package]
name = "openubl-entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
